### ISSUE TITLE
Attempt CRC speedup on tests.

### ISSUE THREAD

**Issue by DaveAtkinsonXMOS** [xmos/lib_xud#189]
Attempt to re-implement suggested CRC speedup from #142 PR review.

**Comment by xross** [comment]
Here are the commits where this was added and then reverted due to some test fails.

commit 9d8538669f623b751236c0810a781dae2743a947
Author: xross <ross@xmos.com>
Date:   Wed May 19 12:20:39 2021 +0100

    Revert "CRC gen speed up"
    
    This reverts commit 7241377d9f7aba1099a27c20a85ab86e89ff1a69.

commit 7241377d9f7aba1099a27c20a85ab86e89ff1a69
Author: xross <ross@xmos.com>
Date:   Mon May 17 14:13:05 2021 +0100

    CRC gen speed up
