### ISSUE TITLE
A halted Endpoint does not issue a STALL if the EP is marked ready

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#58]
An Endpoint is halted by calling XUD_SetStall() however if the Endpoint is subsequently marked as ready e.g. by calling XUD_GetBuffer() then then a stall will not be issued to the host - this is probably not desirable behaviour but can be coded around by the application.

This issue arises since the EP handshake table is only used when the EP is not marked as ready.

**Comment by xross** [comment]
Resolved.

**Comment by xross** [comment]
Fix causes fail in test_bulk_tx_short with the following params:
core_freq: 600
dummy_threads: 4

Reverting causes test to pass.

See #204

**Comment by mbruno-xmos** [comment]
> Fix causes fail in test_bulk_tx_short with the following params:
> core_freq: 600
> dummy_threads: 4
> 
> Reverting causes test to pass.
> 
> See #204

I'm curious if this is due to the STALL condition check on IN endpoints introduced in commit 815ba70, or if it is due to the check on OUT endpoints introduced in commit dd357c2. As far as I can tell, the check on OUT endpoints should not have changed the timing. It did not seem like the extra time taken on the IN endpoint check should have violated anything, though I am not positive.
