### ISSUE TITLE
AN000129 HID Mouse example doesn't operate correctly on Linux hosts

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#60]
Device enumerates correctly but does not cause cursor to spin.

USB trace shows host eventually stops requesting reports. No packet errors.

**Comment by mbanth** [comment]
If you need detailed USB HID knowledge @DaveAtkinsonXMOS, feel free to get in touch with me.

**Comment by DaveAtkinsonXMOS** [comment]
I have got the Beagle Analyzer up and running on Windows and Ubuntu Linux, and obtained a USB protocol trace of the AN000129 application running on both hosts for comparision. Unfortuantely I can't upload the traces, probably because of file size.

 On Windows, we seem to negotiate a full speed connection and then disconnect twice, on the third time we do a reset and go to high speed. We then get an address, exchange a few USB descriptor messages and then reset on a corrupted packet. We repeat the above and finally settle into the device sending a stream of Input Report packets which drive the mouse in a square, as expected. The Beagle analyzer reports 3 errors.

On Linux, I see "<Host connected>" followed by "<High-speed>" (no FS comms) and then I just see alternately "{1 SPLIT}" followed by "{1 ORPHANED}" for about 1200 packets. Then a few SOFs. It struggles along like this for while, before eventually (~3500 packets later?) performing the device enumberation and send input reports, the same as it does on Windows.

I can see that the device enumerates itself as "Product: XNIS Custom Bulk Transfer Device" and doesn't create any device files. Is it possible this is a linux configuration issue rather than a USB issue?

**Comment by xross** [comment]
> I can see that the device enumerates itself as "Product: XMOS Custom Bulk Transfer Device" and doesn't create any device files. Is it possible this is a linux configuration issue rather than a USB issue?

That doesn't sound correct to me . On windows you can remove cache entries using a call called usbdeview or change the PID in the example.

**Comment by DaveAtkinsonXMOS** [comment]
If I remove the device with usbdeview, and replug, same deal. Doesn't seem to work, and appears as "XMOS Custom Bulk Transfer Device".
On  linux, if I do 'lususb -v' I can see that the interface descriptor for the XMOS device reports itself as
      bInterfaceClass          255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
whereas the keyboard and mouse both report
      bInterfaceClass            3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
They also provide
      Interface              0
        HID Device Descriptor:
        ...
which the XMOS device does not.

**Comment by DaveAtkinsonXMOS** [comment]
By the way, I'm assuming that the file ```mic_array_ref.xn``` in the src directory of the application note is a copy and paste error? Obviously we have no mic array here...

**Comment by xross** [comment]
> By the way, I'm assuming that the file `mic_array_ref.xn` in the src directory of the application note is a copy and paste error? Obviously we have no mic array here...

Yes, sounds like an error to me.

**Comment by DaveAtkinsonXMOS** [comment]
And yes, you're correct. That enumeration was a mistake, caused by running the the app that was flashed into the board previously, and not the HID demo, which had been xrun...

**Comment by DaveAtkinsonXMOS** [comment]
Ok, latest observations. On linux, we can see the device enumerating as an HID device in dmesg. The only obviously thing observered is that the value of 'bcdHID' reported is "11.10" which suggest that these bytes are the wrong in the configuration descriptor, because the latest HID spec version is 1.11. Changing lines 84 and 85 of endpoint.xc from
```
    0x10,           /* 2 bcdHID */
    0x11,           /* 3 bcdHID */
```
to
```
    0x11,           /* 2 bcdHID */
    0x01,           /* 3 bcdHID */
```
Makes the dmesg field report "USB HID v1.11".
Changing lines 105 and 106 of the hiDescriptor field in the same way doesn't seem to yield any changes to either the dmesg output, nor that of lsub -v. 
"Logging" would indicate that descriptor type HID_HID is never issued, only HID_REPORT, but that may be becuase of other errors?

**Comment by mbanth** [comment]
> "Logging" would indicate that descriptor type HID_HID is never issued, only HID_REPORT, but that may be becuase of other errors?

I suspect that descriptor type HID_HID refers to the USB HID Descriptor.  Typically, HID USB devices return this descriptor during enumeration along with a USB Interface descriptor and one or more USB End Point descriptors for the HID aspects of the device.  You should be able to see it on a Beagle trace.

Most USB descriptors are self-describing in that they always start with a one byte Length field followed by a 1 byte Type field.  However, USB HID uses two descriptors that do not follow this convention, the HID Report descriptor and the HID Physical descriptor.  The HID descriptor provides the information needed for a parser to handle these atypical descriptors.

**Comment by xross** [comment]
My understanding of the issue is that the mouse demo works just fine on windows and Mac but not Linux (enumerates but cursor does not spin)

I suspect this to be a descriptor compatibility issue or more careful checking of descriptors on linux. Did the bcdHID fix change anything? That seems like exactly the kind of thing that might break the demo.

If all else fails I would just suggest copying descriptors from another (working) HID mouse.

**Comment by DaveAtkinsonXMOS** [comment]
Just seen you message Ross, funnily enough, that's exactly what I've been doing... None of which has made any difference. What I have realised is this: when running the analyzer with split packets filtered out (which cleans up the linux traces no end - I have hubs, and no USB ports directly on the host that aren't USB C...) I can see the the device enumerates okay (okay, it always fails once, but then retries and succeeds), and starts sending Input Report packets. But after a couple of hundred milliseconds (so all of the reports packets have had X: 0, Y:0 in them, so won't have moved the mouse yet) all I can see are ORPHANED messages that seem to be for a non-existant device (in the example I'm looking at right now, communication to "XMOS HID Mouse (7) (BusIdx:6) was proceeding quite happily, and the suddenly there's a bunch of ORPHANED messages for "Unknown Device(6) (BusIdx:0)", "Unknown Device(5) (BusIdx:1)",  "Unknown Device(4) (BusIdx:2)", and  "Unknown Device(2) (BusIdx:3)". No further communication seems to take place with the mouse device. So I think the device is enumerating just fine, as you said, registers all the right modules (spent some time verifying that) but then the USB comms flakes out for some reason as yet to be determined....

**Comment by DaveAtkinsonXMOS** [comment]
Er, have we tried any of the other examples on Linux? As far as I can see, all the examples that I can build, using a checkout of lib_xud and a copy of the tools (i.e. no view file, and therefore anything requiring lib_logging fails to build, it tries to download it but fails for some reason), all these example fail to run on linux for apparently the same reason - just a sea of ORPHANED messages, after an apparently successful enumeration...

**Comment by DaveAtkinsonXMOS** [comment]
Additional information: none of the demos seem to work on Windows, _except_ for the hid mouse demo.

**Comment by DaveAtkinsonXMOS** [comment]
So it would appear that the HID pointer demo now no longer works on Windows either. It was broken by commit [Opts to XUD_Token_In_DI. Speed improvements to stall handling. 933dda1c197](https://github.com/xmos/lib_xud/commit/933dda1c1975a09871bc52813de10078295219b3)

**Comment by DaveAtkinsonXMOS** [comment]
[a2c5fd0 - More ARCH define tidy (removed ARCH_ defines)](https://github.com/xmos/lib_xud/commit/a2c5fd0fb9847fcd7ac049a82f504c25f23432e6) is the first working commit I can find. It works on windows, and on linux it enumerates, and responds to hundreds of Input Report packets, such that the first packet which _should_ drive the mouse pointer (by sending X: -40 Y:0) can be seen. It does not, however, move the mouse pointer, suggesting that there is possibly a linux configuration issue, in addition to the fact that the input packets cease before we see the next non zero pointer coordinates (we are expecting to see a packet with X:0 Y: -40 some time later, and we do not because all bus activity ceases).

**Comment by DaveAtkinsonXMOS** [comment]
For what it's worth, the HID mouse demo doesn't work on xcore200, either. So this is not an XS3-specific problem.

**Comment by DaveAtkinsonXMOS** [comment]
Aha. If we install the linux event test program "evtest" and run it, it finds our device, and it works! This is with the code at a2c5fd0, running on either xcore200 or xcoreai architecture. So this is an issue of the interaction between the hid-generic driver on linux and lib_xud, rather than a purely lib_xud-related problem. It seems that no consumer is provided for the generated events, and maybe the driver then decides not to ask for any more after a while? Why the device doesn't behave like a generic mouse, I don't yet know, as it enumerates as a mouse device and triggers the installation of the usbhid module, as does a real mouse.

**Comment by DaveAtkinsonXMOS** [comment]
What functionality there on linux is also broken by 933dda1c197.

**Comment by DaveAtkinsonXMOS** [comment]
Issue root-ish-caused: something in the kernel/udev hierarchy identifies the XMOS HID mouse demo as a joystick.
```
$ tail -f /var/log/Xorg.0.log
```
show the device being found and then rejected by the windowing system server, and
```
udevadm monitor
```
shows the device being detected as a joystick (search for ID_INPUT_JOYSTICK=1).

**Comment by DaveAtkinsonXMOS** [comment]
Have modified the HID Report Descriptor, by copying the example given in the [USB Device Class Definition for HID, v1.11](https://www.usb.org/document-library/device-class-definition-hid-111), Appendix E10. The device now appears as a mouse on both linux and windows (where it previously only appeared as an HID device). However, The device now fails to operate correctly. On linux, in the kernel log we see "input irq status -75 received". In the USB trace, we can see the Input Report packets are reported as in error.
[AN000129 Linux Failure Input Report Protocol Error.zip](https://github.com/xmos/lib_xud/files/6815146/AN000129.Linux.Failure.Input.Report.Protocol.Error.zip)
