### ISSUE TITLE
Test pass/fail can be altered by running with/without trace

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#96]
Running tests with --trace can cause some tests that really should fail to pass - since the error messages (from a trap, say) get redirected to the trace output.

Mitigation is any CI test runs should be run without trace (probably the default option)

**Comment by DaveAtkinsonXMOS** [comment]
So far: I have added functionality to xsim so that if an exception occurs in the code being simulated (e.g. divide by zero) and the simulator has --trace-to enabled (as it does when --trace is given as an option to xmostest) then the exception notification still goes to stdout, even as it is sent to the trace file. However, it still does not show up in the test output, _if --trace is enabled_. Running the simulator standalone shows the the fix to the simulator works as described, but something must be happening to the xmostest code because the exception does not show up in the test output stream in the xmostest python code. Investigation continues.

**Comment by xross** [comment]
I guess the test still passes when it shouldn't then?

**Comment by DaveAtkinsonXMOS** [comment]
That is correct. It was never going to fail with the failure message sent to a file instead of stdout (which is what happens when the --trace-to argument is given to the simulator, prior to my changes), but even with my changes, the stdout from xsim itself seems to get lost when "--trace" is given as an argument to xmostest. I can see where this argument is processed (lib_xud/tests/helpers.py:158) to add arguments to xsim, but I can't see where it does anything else to modify the redirection or processing of data streams.

**Comment by xross** [comment]
Very odd. Is your proposal to leave this one open until we moved away from xmostest and revisit? If so this sounds sensible to me.

**Comment by DaveAtkinsonXMOS** [comment]
Yes. This is now parked until a resolution of the xmostest->pytest conversion, to see if the issue persists.

**Comment by DaveAtkinsonXMOS** [comment]
I have submitted a proposal to modify the simulator to unconditionally print the unhandled exception messages to stdout. Currently waiting for a response.

**Comment by DaveAtkinsonXMOS** [comment]
The tools team are ok with the proposal, I have submitted a pull request for xsim which currently passes their tests, now need to make sure it passes ours...

**Comment by DaveAtkinsonXMOS** [comment]
Hurrah. With the modification to the simulator, the pytest tests (or at least the subset that I tested) now fail if the UUT code throws an exception, even when tracing is enabled, and pass, with or without tracing, when the code *doesn't* throw an exception. Now need to submit a pull request for xsim, and have it accepted.

**Comment by DaveAtkinsonXMOS** [comment]
I've created the necessary pull requests on GitHub Enterprise, and await the beneficence of the tools folk.

**Comment by DaveAtkinsonXMOS** [comment]
Now merged to latest xsim. Will be in the next release, hopefully.
